steps:
  -
    key: "docker-build"
    label: ":docker:"
    plugins:
      - docker-compose#v3.0.3:
          build: app
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
      BUILDKIT_PROGRESS: plain
  -
    key: "rspec-steps"
    label: ":pipeline: :rspec:"
    command: ".buildkite/rspec-steps | buildkite-agent pipeline upload"
